export enum ErrorCode {
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	NOT_FOUND = 'NOT_FOUND',
	TASK_NOT_FOUND = 'TASK_NOT_FOUND',
	TASK_ARCHIVED = 'TASK_ARCHIVED',
	EMAIL_TAKEN = 'EMAIL_TAKEN',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
}
